Move preprocessor from inside function
It even fails to compile because the header file begins with:

> #ifdef  __cplusplus
> extern "C" {
> #endif

So the compiler complains with the following error:

error: expected unqualified-id before string constant